### ISSUE TITLE
Genial, los botones los has hecho con una única función

### ISSUE THREAD

**Issue by itacademyReact** [adaldin/el-nostre-heroi#3]
Quizás hubiese implementado un `disable` en los botones cuando se llega a los extremos y no se puede retroceder o avanzar más, pero está genial como lo has hecho.

https://github.com/adaldin/el-nostre-heroi/blob/ffce13d77527fc4817077781773504d57039a3b2/src/pages/Escena.js#L26

**Comment by adaldin** [comment]
👌 gracias!
