### ISSUE TITLE
Te dejo solución con styled components

### ISSUE THREAD

**Issue by itacademyReact** [adaldin/el-nostre-heroi#4]
Declarar estilo dinámico para cambiar fondo:

```
export let Main = styled.main`
    background: url(${props => props.image});
    height: 100vh;
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100% 100%;
`;
```

Componente principal que usa el styled:

```
return (
        <Main image={data[counter].img}>
            ...
        </Main>
);
```

https://github.com/adaldin/el-nostre-heroi/blob/ffce13d77527fc4817077781773504d57039a3b2/src/pages/Escena.js#L37

**Comment by adaldin** [comment]
👍  quería hacerlo así pero me lié mucho con los props. Super claro ahora!
